# These are supported funding model platforms

github: Thunderkilll
patreon: thunderkilll
open_collective: thunderkilll
ko_fi: thunderkilll
tidelift: thunderkilll
community_bridge: thunderkilll
liberapay: thunderkilll
issuehunt: thunderkilll
otechie: thunderkilll
lfx_crowdfunding: thunderkilll
custom: # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
